version: "3"

services:
  blue:
    build: ./blue
    container_name: blue_app
    ports:
      - "5001:5000"

  green:
    build: ./green
    container_name: green_app
    ports:
      - "5002:5000"

  nginx:
    image: nginx
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
